exe_files/main/website/views.py
import json
from flask import Blueprint, render_template, jsonify, request, flash, redirect, url_for
from flask_login import login_required, current_user
from . import aiapi
from .models import Chat, LearningStyle, Rubric
from . import db

views = Blueprint('views', __name__)

@views.route('/' , methods=['POST', 'GET'])
@login_required
def home():
    aiapi.clear_chat_history()
    learningstyles = LearningStyle.query.filter_by(student=current_user.id).all()
    
    selected_learning_style_id = request.form.get('selected_learning_style')
    selected_learning_style = LearningStyle.query.get(selected_learning_style_id)
    if selected_learning_style:
        aiapi.add_personality(selected_learning_style.instruction)
    
    return render_template("home.html", user=current_user, learningstyles=learningstyles)

@views.route('/personality', methods=['POST', 'GET'])
@login_required
def personality():
    learningstyles = LearningStyle.query.filter_by(student=current_user.id).all()
    
    if request.method == 'POST':
        name = request.form.get('name')
        description = request.form.get('description')
        instruction = request.form.get('instruction')
        
        new_learning_style = LearningStyle( name=name, description=description, instruction=instruction, student=current_user.id)
        db.session.add(new_learning_style)
        db.session.commit()
        flash("Learning style created", category='success')
        return redirect(url_for('views.personality'))

    return render_template("personality.html", user=current_user, learningstyles=learningstyles)

@views.route('/chathistory')
@login_required
def chathistory():
    chats = Chat.query.filter_by(student=current_user.id).all()
    return render_template("chathistory.html", user=current_user, chats=chats)

@login_required
@views.route("/course1chat", methods=['POST', 'GET'])
def course1chat():
    if request.method == 'POST':
        if 'commit' in request.form:  # Check if the 'commit' button was pressed
            chatdata = aiapi.get_chat_history()
            # Convert chatdata to a JSON string
            chatdata_json = json.dumps(chatdata)
        
            # Create a new Chat object and save it to the database
            new_chat = Chat(course='Math', chatlog=chatdata_json, student=current_user.id)
            db.session.add(new_chat)
            db.session.commit()
            flash('Chat history saved!', category='success')
        else:    
            prompt = request.form['prompt']    
            res = {}
            res['answer'] = aiapi.generateChat(prompt, 1) 
            return jsonify(res), 200
        
    return render_template("c_interface_course1.html", user=current_user)

@login_required
@views.route("/course2chat", methods=['POST', 'GET'])
def course2chat():
    if request.method == 'POST':
        if 'commit' in request.form:  # Check if the 'commit' button was pressed
            chatdata = aiapi.get_chat_history()
            # Convert chatdata to a JSON string
            chatdata_json = json.dumps(chatdata)
        
            # Create a new Chat object and save it to the database
            new_chat = Chat(course='Research', chatlog=chatdata_json, student=current_user.id)
            db.session.add(new_chat)
            db.session.commit()
            flash('Chat history saved!', category='success')
        else:    
            prompt = request.form['prompt']    
            res = {}
            res['answer'] = aiapi.generateChat(prompt, 2) 
            return jsonify(res), 200
        
    return render_template("c_interface_course2.html", user=current_user)

@login_required
@views.route('/grade', methods=['POST', 'GET'])
def grade():
    rubrics = Rubric.query.all()
    selected_rubric_id = request.form.get('selected_rubric')
    selected_rubric = Rubric.query.get(selected_rubric_id)
    rubric_instruction = None
    
    if selected_rubric:
        rubric_instruction = selected_rubric.rubric_instruction
    
    if request.method == 'POST':
        if 'commit' in request.form:  # Check if the 'commit' button was pressed
            chatdata = aiapi.get_chat_history()
            # Convert chatdata to a JSON string
            chatdata_json = json.dumps(chatdata)
        
            # Create a new Chat object and save it to the database
            new_chat = Chat(course='Grade Research', chatlog=chatdata_json, student=current_user.id)
            db.session.add(new_chat)
            db.session.commit()
            flash('Chat history saved!', category='success')
        else:    
            prompt = request.form['prompt']
            res = {}
            res['answer'] = aiapi.generateGrade(rubric_instruction, prompt)
            return jsonify(res), 200
    
    return render_template("grade.html", user=current_user, rubrics=rubrics, rubric_instruction=rubric_instruction)

exe_files/main/website/templates/admin.html
{% extends "base.html" %} {% block title %}Admin{% endblock %} {% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>Admin Page</h1>
        <p class="indextext"> Edit rubric or view all chat history</p>
    </div>
    <div class="row">
        <h2>Add rubric</h2>
        <form method="POST">
            <div class="form-group">
                <label for="course">Course</label>
                <input type="text" class="form-control" id="course" name="course" placeholder="Course name" />
                <label for="instruction">Rubric instructions</label>
                <input type="text" class="form-control" id="instruction" name="instruction"
                    placeholder="Enter instruction" />
            </div>
            <br />
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
    <div class="row">
        <h2>All rubrics</h2>
        {% for rubric in rubrics %}
        <div class="card border-dark">
            <div class="card-header d-flex justify-content-between align-items-center">
                <p>{{rubric.course}}</p>
            </div>
            <div class="card-body">
                <div class="card-text">{{rubric.rubric_instruction}}</div>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="row">
        <h2>All chat history</h2>
        {% for chat in chats %}
        <div class="card border-dark">
            <div class="card-header d-flex justify-content-between align-items-center">
                <p>{{chat.user.name}}</p>
                <p>{{chat.course}}</p>
            </div>
            <div class="card-body">
                <div class="card-text">{{chat.chatlog.replace('\n', '<br>')|safe}}</div>
            </div>
            <div class="card-footer text-muted">{{chat.date_created}}</div>
        </div>
        {% endfor %}
    </div>

</div>
{% endblock %}

exe_files/main/website/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <title>{% block title %}Home{% endblock %}</title>
    {% block style %}{% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" id="home" href="/">Home</a>
                <a class="nav-item nav-link" id="personality" href="/personality">Personality settings</a>
                <a class="nav-item nav-link" id="chathistory" href="/chathistory">Chat history</a>
                {% if current_user.admin %}
                <a class="nav-item nav-link" id="admin" href="/admin">Admin</a>
                {% endif %}
                <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                {% else %}
                <a class="nav-item nav-link" id="login" href="/login">Login</a>
                <a class="nav-item nav-link" id="register" href="/register">Register</a>
                {% endif %}
            </div>
        </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    {% if category == 'error' %}
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% else %}
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endif %}
    {% endfor %}
    {% endif %}
    {% endwith %}
    <div class="container">
        {% block content%}
        {% endblock %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.3.min.js"
        integrity="sha256-pvPw+upLPUjgMXY0G+8O0xUf+/Im1MZjXxxgOcBQBXU=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
        crossorigin="anonymous"></script>
    {% block script %}{% endblock %}
</body>

</html>

exe_files/main/website/templates/c_interface_course1.html
{% extends "base.html" %} {% block title %}Math Chat{% endblock %}
{% block style%}
<style>
  .content {
    font-size: 28px;
  }

  /* Chat container */
  .chat-container {
    flex: 1;
    border: 1px solid #ccc;
    margin: 0 auto;
    padding: 10px;
    overflow-y: auto;
  }

  /* Chat messages */
  .message {
    margin-bottom: 10px;
  }

  .message .sender {
    font-weight: bold;
  }

  .message .content {
    background-color: #F0F0F0;
    padding: 5px;
    border-radius: 5px;
  }

  /* Input area */
  .input-container {
    display: flex;
    margin-top: 10px;
    margin-bottom: 20px;
  }

  .input-box {
    flex: 1;
    padding: 5px;
  }

  .send-button {
    padding: 5px 10px;
    background-color: #4CAF50;
    color: white;
    border: none;
    cursor: pointer;
  }

  .bg-light {
    background-color: #353647 !important;
    margin-left: 15px;
    margin-right: 15px;
  }

  .mb-3 {
    background: skyblue;
    border-radius: 25px;
    margin-top: 5px;
    margin-bottom: 5px;
  }

  .mb-2 {
    background: springgreen;
    border-radius: 25px;
    margin-top: 5px;
    margin-bottom: 5px;
  }

  .message {
    background: skyblue;
  }

  #usermessage {
    background: springgreen;
  }

  #aicontent {
    background: skyblue;
  }

  #usercontent {
    background: springgreen;
  }
</style>
{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <form action="{{ url_for('views.course1chat') }}" method="POST">
      <button type="submit" name="commit" class="btn btn-outline-secondary btn-lg">Save chat</button>
    </form>
  </div>

  <div class="list-group w-auto" id="chat-log">
    <div class="chat-container mb-3">
      <div class="message">
        <span class="sender">Teacher Bot:</span>
        <div class="content" id="aicontent">
          Hi there! I am your AI math teacher, ask me anything about the course!
        </div>
      </div>
    </div>
  </div>

  <div class="input-container">
    <input type="text" id="chat-input" class="input-box" placeholder="Type your message...">
    <button class="send-button" id="gpt-button">Send</button>
  </div>
</div>
{% endblock %}
{% block script %}
<script>
  const input = document.getElementById('chat-input');
  const button = document.getElementById('gpt-button');

  input.addEventListener('keyup', function (event) {
    if (event.key === 'Enter') {
      event.preventDefault(); // Prevents the default behavior of the Enter key

      button.click(); // Trigger a click event on the button
    }
  });
  $("#gpt-button").click(function () {
    var question = $("#chat-input").val();

    let html_data = '';
    html_data += `
      <div class="chat-container mb-2">
        <div class="message" id="usermessage">
          <span class="sender">You:</span>
          <div class="content" id="usercontent">
            ${question}
          </div>
        </div>
      </div>
      `;
    $("#chat-input").val('');
    $("#chat-log").append(html_data);

    //AJAX CALL TO THE SERVER
    $.ajax({
      type: "POST",
      url: "/course1chat",
      data: { 'prompt': question },
      success: function (data) {
        let gpt_data = '';
        gpt_data += `
          <div class="chat-container mb-3">
            <div class="message">
              <span class="sender">Teacher Bot:</span>
              <div class="content" id="aicontent">
                ${data.answer}
              </div>
            </div>
          </div>
          `;
        $("#chat-log").append(gpt_data);
        window.scrollTo(0, document.body.scrollHeight); // Scroll the page to the bottom

      }
    });
    window.scrollTo(0, document.body.scrollHeight); // Scroll the page to the bottom
  });
</script>
{% endblock %}

exe_files/main/website/templates/c_interface_course2.html
{% extends "base.html" %} {% block title %}Math Chat{% endblock %}
{% block style%}
<style>
  .content {
    font-size: 28px;
  }

  /* Chat container */
  .chat-container {
    flex: 1;
    border: 1px solid #ccc;
    margin: 0 auto;
    padding: 10px;
    overflow-y: auto;
  }

  /* Chat messages */
  .message {
    margin-bottom: 10px;
  }

  .message .sender {
    font-weight: bold;
  }

  .message .content {
    background-color: #F0F0F0;
    padding: 5px;
    border-radius: 5px;
  }

  /* Input area */
  .input-container {
    display: flex;
    margin-top: 10px;
    margin-bottom: 20px;
  }

  .input-box {
    flex: 1;
    padding: 5px;
  }

  .send-button {
    padding: 5px 10px;
    background-color: #4CAF50;
    color: white;
    border: none;
    cursor: pointer;
  }

  .bg-light {
    background-color: #353647 !important;
    margin-left: 15px;
    margin-right: 15px;
  }

  .mb-3 {
    background: skyblue;
    border-radius: 25px;
    margin-top: 5px;
    margin-bottom: 5px;
  }

  .mb-2 {
    background: springgreen;
    border-radius: 25px;
    margin-top: 5px;
    margin-bottom: 5px;
  }

  .message {
    background: skyblue;
  }

  #usermessage {
    background: springgreen;
  }

  #aicontent {
    background: skyblue;
  }

  #usercontent {
    background: springgreen;
  }
</style>
{% endblock %}
{% block content %}
<div class="container">
  <div class="row">
    <form action="{{ url_for('views.course2chat') }}" method="POST">
      <button type="submit" name="commit" class="btn btn-outline-secondary btn-lg">Save chat</button>
    </form>
  </div>

  <div class="list-group w-auto" id="chat-log">
    <div class="chat-container mb-3">
      <div class="message">
        <span class="sender">Teacher Bot:</span>
        <div class="content" id="aicontent">
          Hi there! I am your AI research teacher, ask me anything about the course!
        </div>
      </div>
    </div>
  </div>

  <div class="input-container">
    <input type="text" id="chat-input" class="input-box" placeholder="Type your message...">
    <button class="send-button" id="gpt-button">Send</button>
  </div>
</div>
{% endblock %}
{% block script %}
<script>
  const input = document.getElementById('chat-input');
  const button = document.getElementById('gpt-button');

  input.addEventListener('keyup', function (event) {
    if (event.key === 'Enter') {
      event.preventDefault(); // Prevents the default behavior of the Enter key

      button.click(); // Trigger a click event on the button
    }
  });
  $("#gpt-button").click(function () {
    var question = $("#chat-input").val();

    let html_data = '';
    html_data += `
      <div class="chat-container mb-2">
        <div class="message" id="usermessage">
          <span class="sender">You:</span>
          <div class="content" id="usercontent">
            ${question}
          </div>
        </div>
      </div>
      `;
    $("#chat-input").val('');
    $("#chat-log").append(html_data);

    //AJAX CALL TO THE SERVER
    $.ajax({
      type: "POST",
      url: "/course2chat",
      data: { 'prompt': question },
      success: function (data) {
        let gpt_data = '';
        gpt_data += `
          <div class="chat-container mb-3">
            <div class="message">
              <span class="sender">Teacher Bot:</span>
              <div class="content" id="aicontent">
                ${data.answer}
              </div>
            </div>
          </div>
          `;
        $("#chat-log").append(gpt_data);
        window.scrollTo(0, document.body.scrollHeight); // Scroll the page to the bottom

      }
    });
    window.scrollTo(0, document.body.scrollHeight); // Scroll the page to the bottom
  });
</script>
{% endblock %}

exe_files/main/website/templates/chathistory.html
{% extends "base.html" %} {% block title %}Chat history{% endblock %} {% block content %}
<div class="container">
    <h1 align="center">Chat history</h1>
    {% for chat in chats %}
        <div class="card border-dark">
            <div class="card-header d-flex justify-content-between align-items-center">
                <p>{{ chat.course }}</p>
            </div>
            <div class="card-body">
                <div class="card-text">{{ chat.chatlog.replace('\n', '<br>')|safe }}</div>
            </div>
            <div class="card-footer text-muted">{{ chat.date_created }}</div>
        </div>
    {% endfor %}
</div>
{% endblock %}

exe_files/main/website/templates/grade.html
{% extends "base.html" %} {% block title %}Grade Assessment{% endblock %}
{% block style%}

<style>
  .content {
    font-size: 28px;
  }
  .chat-container {
    flex: 1;
    border: 1px solid #ccc;
    margin: 0 auto;
    padding: 10px;
    overflow-y: auto;
  }
  .mb-3 {
    background: skyblue;
    border-radius: 25px;
    margin-top: 5px;
    margin-bottom: 5px;
  }
  .message {
    margin-bottom: 10px;
  }
  #aicontent {
    background: skyblue;
  }

  .message {
    background: skyblue;
  }

  .message .content {
    background-color: #F0F0F0;
    padding: 5px;
    border-radius: 5px;
  }
</style>
{% endblock %}
{% block content %}
<div class="container">
  <br />
  <div class="row">
    <div class="col">
      <form method="POST" action="{{ url_for('views.grade') }}">
        <select class="form-select" aria-label="None" name="selected_rubric">
          <option selected>None</option>
          {% for rubric in rubrics %}
          <option value="{{ rubric.id }}">{{ rubric.course }}</option>
          {% endfor %}
        </select>
        <br />
        <div class="form-group">
          <label for="assessment">Assessment</label>
          <textarea class="form-control" id="assessment" name="prompt" rows="10"></textarea>
        </div>
        <br />
        <button type="submit" class="btn btn-outline-primary btn-lg" id="grade-button">Grade Assessment</button>
        <button type="submit" name="commit" class="btn btn-outline-secondary btn-lg">Save grading</button>
      </form>
    </div>
    <div class="col">
      <h2>Result</h2>
      <div class="list-group w-auto" id="chat-log">
        <div class="chat-container mb-3">
          <div class="message">
            <span class="sender">Teacher Bot:</span>
            <div class="content" id="aicontent">
              Hi there! I am here to grade your work! Choose the required rubric and copy your work into the text label.
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block script %}
<script>
  $("#grade-button").click(function (event) {
    event.preventDefault(); // Prevent the default form submission behavior
  
    var assessment = $("#assessment").val();
    var selectedRubric = $("select[name='selected_rubric']").val();
  
    // AJAX CALL TO THE SERVER
    $.ajax({
      type: "POST",
      url: "/grade",
      data: {
        'selected_rubric': selectedRubric,
        'prompt': assessment
      },
      success: function (data) {
        let gpt_data = '';
        gpt_data += `
                <div class="chat-container mb-3">
                    <div class="message">
                        <span class="sender">Teacher Bot:</span>
                        <div class="content" id="aicontent">
                            ${data.answer}
                        </div>
                    </div>
                </div>
            `;
        $("#chat-log").append(gpt_data);
      }
    });
  });
</script>
{% endblock %}

exe_files/main/website/templates/home.html
{% extends "base.html" %} {% block title %}Homepage{% endblock %}
{% block style%}
<style>
    .small {
        font-size: 24px;
    }

    .font-weight-bold {
        font-size: 32px;
    }

    .h1 {
        font-size: 38px;
    }

    .indextext {
        font-size: 22px;
    }

    .rounded-3 {
        border-radius: 0.3rem !important;
    }

    .bg-dark {
        background-color: #212529 !important;
    }

    .text-white {
        color: #fff !important;
    }

    .p-5 {
        padding: 3rem !important;
    }

    .h-100 {
        height: 100% !important;
    }

    *,
    ::after,
    ::before {
        box-sizing: border-box;
    }

    stylesheet voor user-agents div {
        display: block;
    }

    .bg-light {
        background-color: #353647 !important;
        margin-left: 15px;
        margin-right: 15px;
    }

    .bg-grey {
        background-color: #e3e3e3;
    }

    .bg-white {
        background-color: #ffffff !important;
    }

    .border {
        border: 1px solid #dee2e6 !important;
    }

    .btn-outline-secondary {
        color: #ffffff;
    }

    .subtitle {
        color: #000000;
    }

    .editrubric {
        color: #000000
    }

    .submitwhite {
        color: #000000;

    }

    label {
        color: #ffffff
    }

    #theme {
        color: #000000
    }
</style>
{% endblock %}
{% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>Education AI</h1>
        <p class="indextext"> Learn with your personal AI teacher, choose a course and get started!</p>
        <h2>Select learning style</h2>
        <form method="POST" action="{{ url_for('views.home') }}">
            <select class="form-select" aria-label="None" name="selected_learning_style">
                <option selected>None</option>
                {% for learningstyle in learningstyles %}
                    <option value="{{ learningstyle.id }}">{{ learningstyle.name }}</option>
                {% endfor %}
            </select>
            <button type="submit" class="btn btn-outline-primary btn-lg">Update AI</button>
        </form>
    </div>
    <div class="row">
        <h2 class="subtitle">Courses</h2>
        <div class="col-md-6">
            <div class="h-100 p-5 text-white bg-dark rounded-3">
                <h2>Math</h2>
                <p class="small">Get your math question answered or grade your paper</p>
                <a href="/course1chat"><button type="button" class="btn btn-outline-primary btn-lg">Teach</button></a>
                
            </div>
        </div>
        <div class="col-md-6">
            <div class="h-100 p-5 bg-grey border rounded-3">
                <h2>Research</h2>
                <p class="small">Get your research question answered or grade your paper</p>
                <a href="/course2chat"><button type="button" class="btn btn-outline-primary btn-lg">Teach</button></a>
                <a href="/grade"><button type="button" class="btn btn-outline-secondary btn-lg" style="color: black;">Grade Assessment</button></a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

exe_files/main/website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content %}
<form method="POST">
    <h3 align="center">Log in</h3>
    <div class="form-group">
        <label for="email">Email</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" />
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Enter password" />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

exe_files/main/website/templates/personality.html
{% extends "base.html" %} {% block title %}Personality settings{% endblock %} {% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>Personality settings</h1>
        <p class="indextext"> Create & view your learning style</p>
    </div>
    <div class="row">
        <h2>Create learning style</h2>
        <form method="POST">
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Enter name" />
                <label for="description">Description</label>
                <input type="text" class="form-control" id="description" name="description" placeholder="Enter description" />
                <label for="instruction">Instruction (e.g. Use generation-z slang during the chat)</label>
                <input type="text" class="form-control" id="instruction" name="instruction" placeholder="Enter instruction" />
            </div>
            <br />
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
    <div class="row">
        <h2>View learning styles</h2>
        {% for learningstyle in learningstyles %}
        <div class="card border-dark">
            <div class="card-header d-flex justify-content-between align-items-center">
                <p>{{ learningstyle.name}}</p>
            </div>
            <div class="card-body">
                <div class="card-text">{{ learningstyle.description }}</div>
            </div>
            <div class="card-footer text-muted">{{ learningstyle.instruction }}</div>
        </div>
        {% endfor %}
    </div>

</div>
{% endblock %}

exe_files/main/website/templates/register.html
{% extends "base.html" %} {% block title %}Register{% endblock %} {% block content %}
<form method="POST">
    <h3 align="center">Sign Up</h3>
    <div class="form-group">
        <label for="name">Name</label>
        <input type="text" class="form-control" id="name" name="name" placeholder="Enter name" />
        <label for="email">email</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter email" />
        <label for="password1">Password</label>
        <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter password" />
        <label for="password2">Confirm Password</label>
        <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm password" />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}